config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|zh/ do
    root 'pages#welcome'
      get 'upcoming_events' => 'pages#upcoming_events'
      get 'about_us' => 'pages#about_us'
      get 'service_sched' => 'pages#service_sched'
      get 'contact_us' => 'pages#contact_us'
      get 'testimonies' => 'pages#testimonies'
      get 'resources' => 'pages#resources'
      get 'welcome' => 'pages#welcome'
      get 'service_sched_2014' => 'pages#service_sched_2014'
      get 'login_register' => 'pages#login_register'

  end
  
  

    resources :pages

end

app/models/user.rb
class User < ActiveRecord::Base

  	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence:true, length:{maximum: 50}
	validates :email, presence:true, length: {maximum: 255}, 
	format: { with: VALID_EMAIL_REGEX }, uniqueness:{ case_sensitive: false }
	has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_filter :set_locale
 
  
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale 
  end
  
end

app/controllers/page_controller_controller.rb
class PageControllerController < ApplicationController
  def home
  end

  def upcoming_news
  end

  def about_us
  end

  def service_sched
  end

  def testimonies
  end

  def pictures
  end

  def contact_us
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def upcoming_events
  end

  def about_us
  end

  def service_sched
  end

  def contact_us
  end

  def testimonies
  end

  def resources
  end

  def service_sched_2014
  end

  def login_register
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/set_language_controller.rb
class SetLanguageController < ApplicationController
  def english
  	I18n.locale = :en
  	set_session_and_redirect
  end

  def chinese
  	I18n.locale = :zh
  	set_session_and_redirect
  end

  private
    def set_session_and_redirect
      session[:locale] = I18n.locale
      redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to :root
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 #Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Bread of Life Christian Church"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'current' : ''
  content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/set_language_helper.rb
module SetLanguageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer" id="webFooter" bgcolor="#333">
	<div class="container-fluid">
                <div class="row">
                    <div class="col-md-3 col-sm-6 margin30">

                        <div class="footer-col">
                            <h3>About BOLCC</h3>
                            <p>
                                Bread of Life Christian Church is a non-denominational Chrstian church located in Norcross, GA led by pastors Yung Chou (Sam) and Felicia Hsu. We are a sister church of the Taipei Bread of Life Church. We welcome you to join our service every Sunday at 10:45 am. 
                            </p>
                        </div>                        
                    </div><!--footer col-->
                    <div class="col-md-3 col-sm-6 margin30">
                        <div class="footer-col">
                            <h3>Contact</h3>

                            <ul class="list-unstyled contact">
                                <li><p><strong><i class="fa fa-map-marker"></i> Address:</strong> 4350 Peachtree Industrial Blvd. 
								Suite 500, Norcross, GA 30071</p></li> 
                                <li><p><strong><i class="fa fa-envelope"></i> Mail Us:</strong> <a href="#">yungchouhsu@gmail.com</a></p></li>
                                <li> <p><strong><i class="fa fa-phone"></i> Phone:</strong>678-979-8143</p></li>

                            </ul>
                        </div>                        
                    </div><!--footer col-->
                    <div class="col-md-3 col-sm-6 margin30">
                        <div class="footer-col">
                            <h3>Featured Work</h3>
                            <ul class="list-inline f2-work">
                                <li><a href="portfolio-single.html"><img src="img/img-1.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-2.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-3.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-4.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-5.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-6.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-7.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-8.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="portfolio-single.html"><img src="img/img-9.jpg" class="img-responsive" alt=""></a></li>
                            </ul>
                        </div>                        
                    </div><!--footer col-->
                    <div class="col-md-3 col-sm-6 margin30">
                        <div class="footer-col">
                            <h3>Newsletter</h3>
                            <p>
                                If you would like to suscribe to our church annoucements, please enter your e-mail below.
                            </p>
                            <form role="form" class="subscribe-form">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Enter email to subscribe">
                                    <span class="input-group-btn">
                                        <button class="btn  btn-theme-dark btn-lg" type="submit">Ok</button>
                                    </span>
                                </div>
                            </form>
      </div>
 </div>

app/views/layouts/_leaders.html.erb
<div class="divide100">


                <div class="col-md-12 margin20">
                    <h1 class="wow animated bounceInUp animated heading"> Our Pastors</h1>
                </div>
        
            <div class="row">


                <div class="col-md-6">
                    <%= image_tag "pastors.jpg", :class=>"img-responsive" %>
                </div>

                <div class="col-md-6 margin20">
                    <h3 class="heading">A little about us</h3>
                    <p align="left">
                       Insert brief introduction for the pastors.
                       <br>
                    </p>
                </div>

            </div><!--about intro-->


</div>

app/views/layouts/application.html.erb
<div id="wrap">

    <div id="main">

    <head>
    <title><%= full_title(yield(:title)) %></title>
      <title>Atlanta Bread of Life Christian Church</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>


    <div id="wrapper">
    <div id="container">
    <div id="lang_bar" align="right">
    <%= link_to_unless I18n.locale == :en, "English", locale: :en %> |
      <%= link_to_unless I18n.locale == :zh, "中文", locale: :zh%>
      </div>
    <%= render 'shared/navigation' %>

    <div id="content">
    <%= yield %>
    </div>


    </div>

</div>  
</div>
</div>          

<div id="footer5">
<%= render 'layouts/footer' %>
</div>

</div>

app/views/pages/about_us.html.erb
<% provide(:title, "About") %>
<%= stylesheet_link_tag "about" %>

<!--<header>
<img id="imgformat" src="assets/banner.jpg" style="height:auto; width:auto; min-width:1600px; max-height:200px;" id="aboutbanner">
</header> -->
 
<div class="divide80"></div>

<div class="center-heading">
<h1 class="wow animated fadeinDown animated"> ABOUT US </h1>
<span class="center-line"</span>
</div>

        <div class="container">
            <div class="row">
                <div class="col-md-6 margin20">
                    <h3 class="heading"> <%= t(:about)%> </h3>
                    <p align="left">
                       本 堂由徐永宙傳道在2005年4月成立，秉承母堂－台北靈糧堂的異象【傳承使命．權能宣教．力行聖經．邁向榮耀】，要在亞特蘭大建立一間榮耀的教會。

                       我 們期望弟兄姊妹人人在四個重點方面努力:
                       能夠跟隨聖靈的引導，讓神在生命中掌權；
                       渴慕神的話語，能夠力行並宣講聖經；
                       能夠活出聖潔的生活，有美好的見證；
                       並且透過團隊的服事，能夠開展聖工祝福別人；

                       我們相信因著亞特蘭大靈糧堂的建立，神會藉著我們生命改變的見證，真實地去影響所接觸到的每一個人，將神的慈愛、喜樂、平安帶給個人，家庭，職場，社區， 甚至萬國萬民中。

                       我 們採用小組教會的架構，邀請每個到教會來的人加入小組，您在小組中將能學習並經歷到: 互相扶持，彼此代禱，相親相愛，堅立信心，靈命更新增長，並且廣傳福音，活出有意義的「標竿人生」。
                       <br>
                       <br>

                       We welcome you to join us for service every Sunday at 10:45 am. 
                    </p>
                </div>

                <div class="col-md-6">
                <%= image_tag "churchgroup.jpg", :class=>"img-responsive" %>
                </div>

                <div  id="pastors">
                <%= render 'layouts/leaders' %>
                </div>
            </div><!--about intro-->



            
<div class="flexslider" id="flexslider">
  <ul class="slides">
    <li>
      <img src="assets/10yrv2.png" />
    </li>
    <li>
      <img src="assets/sportsday-big.png" />
    </li>
    <li>
      <img src="assets/advent-big.png" />
    </li>
  </ul>
</div>

<!-- Place in the <head>, after the three links -->
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider();
  });
</script>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

app/views/pages/home.html.erb
 <body class="maintenance-page">
        <div class="container text-center">
            <div class="divide80"></div>
            <h1><a href="index.html">Atlanta Bread of Life Christian Church</a></h1>
            <hr>
            <div class="divide40"></div>
            <div class="main-text">
                Our website is under maintenance<br>
                <span>We are back after sometime.</span>
            </div>
            <div class="divide80"></div>
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="row">
                        <div class="col-sm-6 margin40">
                            <div class="maintenance-box">
                                <i class="fa fa-warning"></i>
                                <h4>Reason the site down?</h4>
                                <p>
                                    We are in process of developing for you to use :)
                                </p>
                            </div><!--maintenance box-->
                        </div>
                        <div class="col-sm-6 margin40">
                            <div class="maintenance-box">
                                <i class="fa fa-clock-o"></i>
                                <h4>Estimate downtime?</h4>
                                <p>
                                    1-2 Weeks
                                </p>
                            </div><!--maintenance box-->
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

app/views/pages/login_register.html.erb
<div class="divide80"> </div>
<body background="temp_bg.jpg">
<div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div role="tabpanel">

                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs text-center" role="tablist">
                            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">Login</a></li>
                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Register</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="login">
                                <form>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                                    </div>                                  
                                    <div class="pull-left">

                                        <p><a href="#">Forget password?</a></p>

                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-theme-dark">Login</button>
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div><!--login tab end-->
                            <div role="tabpanel" class="tab-pane" id="profile">
                                <form>
                                    <div class="form-group">
                                        <label for="exampleInputname">Name</label>
                                        <input type="text" class="form-control" id="exampleInputname" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail11">Email address</label>
                                        <input type="email" class="form-control" id="exampleInputEmail11" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword11">Password</label>
                                        <input type="password" class="form-control" id="exampleInputPassword11" placeholder="Password">
                                    </div>    
                                    <div class="form-group">
                                        <label for="exampleInputPassword111">Re-Password</label>
                                        <input type="password" class="form-control" id="exampleInputPassword111" placeholder="Password">
                                    </div> 
                                    <div class="pull-left checkbox">
                                        <label>
                                            <input type="checkbox"> Accept terms & condition.
                                        </label>

                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-theme-dark btn-lg">Register</button>
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div><!--register tab end-->
                        </div>

                    </div>
                </div>
            </div>
        </div>

        </body>

app/views/pages/resources.html.erb
 <div class="divide80"></div>

<div class="center-heading">
<h1 class="wow animated fadeInDown animated"> RESOURCES </h1>
<span class="center-line"</span>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3 class="heading">Links</h3>
            <p align="left">
              <ul class="circle" id="resources-list">
                <li><%= link_to("台北靈糧堂","http://www.llc.org.tw/")%> </li>
                <li><%= link_to("生命河靈糧堂","http://www.llc.org.tw/")%> </li>
                <li><%= link_to("好消息Good TV電視台","http://www.goodnews.org.tw/")%> </li>
                <li><%= link_to("佳音Love聯播網","http://www.llc.org.tw/")%> </li>
                <li><%= link_to("讚美之泉Stream of Praise","http://www.sop.org/")%> </li>
                <li><%= link_to("有情天音樂","http://www.heaventunes.com/")%> </li>
              </ul
            </p>
        </div>


        <h3 class="heading">軟 體下載</h3>
        <div class="col-md-6">
        <%= link_to(image_tag("cesong_rollover.gif", :alt => "cesong", :title => "CE Song", :class=> "img-responsive"), "http://www.atlantabolcc.org/atlantabolcc.org/Program/cesong/cesong_index_ZH.html") %>
        <%= link_to(image_tag("cebible_rollover.gif", :alt => "cebible", :title => "CE Bible", :class=> "img-responsive"), "http://www.atlantabolcc.org/atlantabolcc.org/Program/cebible/cebible_index_ZH.html") %>
        </div>
</div>


</div>


 <div class="divide80"></div>

app/views/pages/service_sched_2014.html.erb
<div class="divide80"></div>

<div class="center-heading">
<h1 class="wow animated fadeinDown animated"> SERVICE SCHEDULE</h1>
<span class="center-line"</span>
</div>


<div class="container">
    <div class="row">
        <div class="col-sm-2 ">
            <div class="sidebar-box margin40">
                <h4>Categories</h4>
                <ul class="list-unstyled cat-list">
                    <li> <%= link_to "2014",   service_sched_2014_path %> <i class="fa fa-angle-right"></i></li>
                    <li> <%= link_to "2015",   service_sched_path %>  <i class="fa fa-angle-right"></i></li>
                </ul>
            </div><!--sidebar-box-->
           
        </div><!--sidebar col end-->


 <div class="container">
     <div class="row">
     <div class="col-md-6 margin20">
        <h2> 2014年 </h2>
        <table class="table table-striped table-bordered table-nonfluid">
        <thead>
            <tr>
                <th>日期</th>
                <th>講員</th>
                <th>主題</th>
                <th>MP3</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>04/27</td>
                <td>徐永宙牧師</td>
                <td>阿摩司書，何西阿書，彌迦書——<br> 
                    行公義，好憐憫，<br>存謙卑的心與神同行</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140427.mp3",  :target => "_blank" %> </td>
            </tr>
            <tr>
                <td>05/18</td>
                <td>林大中牧師</td>
                <td>看見神蹟奇事就信了</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140518.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td rowspan=7>05/29</td>
                <td rowspan=7 >弟兄姊妹受洗見證</td>
                <td>Lucy Deng</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/Lucy_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>Stephanie Gao</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/Stephanie_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>Juli Morris</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/Juli_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>葉燕珍</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/YenZhenYeh_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>林清清</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/ChinChinLin_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>管玉華</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/YuHua_320.wmv",  :target => "_blank" %></td>
            </tr>
           <tr>
                <td>周維波</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/WeiPoChou_320.wmv",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>06/01</td>
                <td>陳德玉牧師</td>
                <td>大能的勇士，起來爭戰</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140601.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>06/08</td>
                <td>徐永宙牧師</td>
                <td>上帝記得你</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140608.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>06/15</td>
                <td>陳德玉牧師</td>
                <td>禱告是答案</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140615.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>06/22</td>
                <td>徐永宙牧師</td>
                <td>耶利米書 ——當為你所居住之城禱告</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140622.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>06/29</td>
                <td>陳德玉牧師</td>
                <td>牧者的三個提醒</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/2Q/140629.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>07/06</td>
                <td>毛應清弟兄</td>
                <td>約翰福音 —— 人若渴了，<br>可以到我這裡來喝</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140706.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>07/13</td>
                <td>徐永宙牧師</td>
                <td>耶利米書 ——當為你所<br>居住之城禱告</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140727.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>07/20</td>
                <td>陳德玉牧師</td>
                <td>將黑暗推出去</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140720.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>07/27</td>
                <td>徐永宙牧師</td>
                <td>約翰一書 —— 彼此相愛</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140727.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>08/03</td>
                <td>徐永宙牧師</td>
                <td>猶大書 —— 返璞歸真</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140803.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>08/10</td>
                <td>王惠國弟兄</td>
                <td>從讀經到作門徒</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140810.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>08/17</td>
                <td>陳德玉牧師</td>
                <td>挺身昂首</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140817.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>08/24</td>
                <td>陳德玉牧師</td>
                <td>挺身昂首(2) 憑著信心求</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140824.mp3",  :target => "_blank" %></td>
            </tr>
            <tr>
                <td>08/31</td>
                <td>徐永宙牧師</td>
                <td>哈該書 —— 建殿</td>
                <td><%= link_to "收聽","http://atlantabolcc.org/sermon/sermon_mp3/2014/3Q/140831.mp3",  :target => "_blank" %></td>
            </tr>
        </tbody>
    </table>    
    </div>
</div>

</div>
</div>

app/views/pages/testimonies.html.erb
<h1>Example Webshop</h1>
<p>Welcome to this webshop.</p>

<p><b>I18n.locale:</b> 
<%= I18n.locale %>
</p>

app/views/pages/upcoming_events.html.erb
<h1>Pages#upcoming_events</h1>
<p>Find me in app/views/pages/upcoming_events.html.erb</p>

app/views/pages/welcome.erb
<section class="block">
<div id="myCarousel" class="carousel slide fill" data-ride="carousel">
            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>   
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner" align="center">
    <div class="item active">
      <%= image_tag "10yrv2.png", :class=>"img-responsive" %>
      <div class="carousel-caption">
          <h3></h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "sportsday-big.png", :class=>"img-responsive" %>
      <div class="carousel-caption">
          <h3></h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "advent-big.png", :class=>"img-responsive" %>
      <div class="carousel-caption">
          <h3></h3>
      </div>
    </div>
  </div>
 
  <!-- Controls -->
  <div class="pull-center">
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
  </div>
</div> 
</section>
<!-- Carousel -->


</body>

app/views/set_language/chinese.html.erb
<h1>SetLanguage#chinese</h1>
<p>Find me in app/views/set_language/chinese.html.erb</p>

app/views/set_language/english.html.erb
<h1>SetLanguage#english</h1>
<p>Find me in app/views/set_language/english.html.erb</p>

app/views/shared/_navigation.html.erb
<header class="navbar-default" >
	  <div class="container-fluid" data-no-turbolink>

	    <nav>

	    <%= link_to(image_tag("bolcc_logo.png"), root_path) %>
	    

	      <ul class="nav navbar-nav navbar-right yamm fixed">
	        <li><%= link_to (t :home),   welcome_path%></li>
	        <li><%= link_to "About", about_us_path%></li>
	        <li><%= link_to "Service", service_sched_path%> </li>
	        <li class="dropdown">  
	    		<a href="" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100" data-close-others="false"> Schedule <b class="caret"></b>
	    		</a>
	    		<ul class="dropdown-menu">
	       			 <li><%= link_to "Upcoming Events",   upcoming_events_path %></li>
	        		 <li><%= link_to "Service Schedule",  service_sched_path %></li>
	    		</ul>
			</li>  
	        <li><%= link_to "Pictures",   'https://www.flickr.com/photos/bolcc_atlanta',  :target => "_blank" %></li>
	        <li><%= link_to "Testimonies", testimonies_path %> </li>
	        <li><%= link_to "Resources",   resources_path %>   </li>
	        <li><%= link_to "Sign In",   login_register_path%>   </li>

	      </ul>
	    </nav>
	  </div>
	</header>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>